#pragma once

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_zemco_mediatoasts_handlers_WindowsMediaHandler */

#ifndef _Included_dev_zemco_mediatoasts_handlers_WindowsMediaHandler
#define _Included_dev_zemco_mediatoasts_handlers_WindowsMediaHandler
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     dev_zemco_mediatoasts_handlers_WindowsMediaHandler
     * Method:    initialize
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_dev_zemco_mediatoasts_handlers_WindowsMediaHandler_initialize
    (JNIEnv*, jobject);

    /*
     * Class:     dev_zemco_mediatoasts_handlers_WindowsMediaHandler
     * Method:    dispose
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_dev_zemco_mediatoasts_handlers_WindowsMediaHandler_dispose
    (JNIEnv*, jobject);

#ifdef __cplusplus
}
#endif
#endif
