/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_zemco_mediatoasts_handlers_LinuxMediaHandler */

#ifndef _Included_dev_zemco_mediatoasts_handlers_LinuxMediaHandler
#define _Included_dev_zemco_mediatoasts_handlers_LinuxMediaHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_zemco_mediatoasts_handlers_LinuxMediaHandler
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dev_zemco_mediatoasts_handlers_LinuxMediaHandler_initialize
  (JNIEnv *, jobject);

/*
 * Class:     dev_zemco_mediatoasts_handlers_LinuxMediaHandler
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dev_zemco_mediatoasts_handlers_LinuxMediaHandler_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
